spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:com/example/springbootmybatisplus/mapper/xml/*.xml
  type-aliases-package: classpath:com.example.springbootmybatisplus.entity